version: '3.7'

services:
  web:
    build:
      context: .
      # dockerfile: Dockerfile
    volumes:
      - .:/api
    ports:
      - 3000:3000
    command: pipenv run python manage.py runserver 0.0.0.0:8000
  #   depends_on:
  #     - db
      
  # db:
  #   image: postgres:10.1-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/